import Head from 'next/head'
import { useRef } from 'react';
import Landing from '../components/Landing';

export default function Home() {
  const ref = useRef();

  return (
      <div>
        <Head>
          <title>GRight</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Landing></Landing>
      </div>
  )
}
